//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FyreWinClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FyreWinClient.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sh-v1.0e.ulx.
        /// </summary>
        internal static string GameFile {
            get {
                return ResourceManager.GetString("GameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;hints title=&quot;Trouble in Grubbers&quot;&gt;
        ///			&lt;topic title=&quot;What do I do?&quot;&gt;
        ///				&lt;hint id=&quot;1&quot;&gt;You hear voices nearby.&lt;/hint&gt;
        ///				&lt;hint id=&quot;2&quot;&gt;Listen to the voices.&lt;/hint&gt;
        ///				&lt;hint id=&quot;3&quot;&gt;You need to get a better angle.&lt;/hint&gt;
        ///				&lt;hint id=&quot;4&quot;&gt;Notice those crates?&lt;/hint&gt;
        ///				&lt;hint id=&quot;5&quot;&gt;Climb up the crates to get to the roof.&lt;/hint&gt;
        ///			&lt;/topic&gt;
        ///			&lt;topic title=&quot;How do I escape the mercenaries?&quot;&gt;
        ///				&lt;hint id=&quot;1&quot;&gt;Run!&lt;/hint&gt;
        ///			&lt;/topic&gt;
        ///			&lt;topic title=&quot;There&apos;s nowhere to go!&quot;&gt;
        ///				&lt;hint id=&quot;1&quot;&gt;You ca [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hints {
            get {
                return ResourceManager.GetString("hints", resourceCulture);
            }
        }
        
        internal static byte[] sh_v1_0e {
            get {
                object obj = ResourceManager.GetObject("sh_v1_0e", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Shadow in the Cathedral.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: 1.0.20091030Std.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
