/*
 *  DO NOT EDIT THIS CLASS.
 * 
 *  This class is generated by a tool and should not be edited. If you need to change the functionality of 
 *  this class, you should discuss your changes with the team and they should be implemented in the
 *  appropriate template.
 * 
 */
using System;
using System.Data;
using System.Collections.Generic;
using System.ComponentModel;

namespace #rootNamespace#.DataLayer
{
    /// <summary>
    /// Data Collection class that represents a BindingList<T> of #tableName#Data objects.
    /// </summary>
    [Serializable()]
    public class #tableName#DataCollection : BindingList<#rootNamespace#.DataLayer.#tableName#Data>
    {

    }
}
