//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FyreWinClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FyreWinClient.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Gallows {
            get {
                object obj = ResourceManager.GetObject("Gallows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sl-v1.05xe.ulx.
        /// </summary>
        internal static string GameFile {
            get {
                return ResourceManager.GetString("GameFile", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap GrubbersChase {
            get {
                object obj = ResourceManager.GetObject("GrubbersChase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;hints title=&quot;Trouble in Grubbers&quot;&gt;
        ///			&lt;topic title=&quot;What do I do?&quot;&gt;
        ///				&lt;hint id=&quot;1&quot;&gt;You hear voices nearby.&lt;/hint&gt;
        ///				&lt;hint id=&quot;2&quot;&gt;Listen to the voices.&lt;/hint&gt;
        ///				&lt;hint id=&quot;3&quot;&gt;You need to get a better angle.&lt;/hint&gt;
        ///				&lt;hint id=&quot;4&quot;&gt;Notice those crates?&lt;/hint&gt;
        ///				&lt;hint id=&quot;5&quot;&gt;Climb up the crates to get to the roof.&lt;/hint&gt;
        ///			&lt;/topic&gt;
        ///			&lt;topic title=&quot;How do I escape the mercenaries?&quot;&gt;
        ///				&lt;hint id=&quot;1&quot;&gt;Run!&lt;/hint&gt;
        ///			&lt;/topic&gt;
        ///			&lt;topic title=&quot;There&apos;s nowhere to go!&quot;&gt;
        ///				&lt;hint id=&quot;1&quot;&gt;You ca [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hints {
            get {
                return ResourceManager.GetString("hints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///&lt;meta content=&quot;text/html; charset=utf-8&quot; http-equiv=&quot;Content-Type&quot; /&gt;
        ///&lt;title&gt;The Shadow in the Cathedral - Game Hints&lt;/title&gt;
        ///
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///
        ///hide {
        ///	display:block;
        ///}
        ///
        ///show {
        ///	display:none;
        ///}
        ///
        ///&lt;/style&gt;
        ///
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        ///
        ///	var skipToggle = 0;
        ///
        ///	&lt;!--
        ///	
        ///	function toggleQuestion(answers) {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hintTemplate {
            get {
                return ResourceManager.GetString("hintTemplate", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap InJail {
            get {
                object obj = ResourceManager.GetObject("InJail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JackInBallGown {
            get {
                object obj = ResourceManager.GetObject("JackInBallGown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JackInDisguise {
            get {
                object obj = ResourceManager.GetObject("JackInDisguise", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JackInSimpleDress {
            get {
                object obj = ResourceManager.GetObject("JackInSimpleDress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MaidenHouse {
            get {
                object obj = ResourceManager.GetObject("MaidenHouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MeetingBobby {
            get {
                object obj = ResourceManager.GetObject("MeetingBobby", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rightpage {
            get {
                object obj = ResourceManager.GetObject("rightpage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] sl_v2_0e {
            get {
                object obj = ResourceManager.GetObject("sl_v2_0e", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jack Toresal and The Secret Letter.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: 1.07.20090923 DEMO.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
