/*
 *  DO NOT EDIT THIS CLASS.
 * 
 *  This class is generated by a tool and should not be edited. If you need to change the functionality of 
 *  this class, you should discuss your changes with the team and they should be implemented in the
 *  appropriate template.
 *  
 */
using System; 
using System.Data; 
using System.Data.SqlClient;
using System.Collections.Generic;
using #rootNamespace#.DataLayer;

namespace #rootNamespace#.BusinessLayer {
    
    [Serializable()]
    public abstract class #spName#Base {
        [NonSerialized]
        private #spName#Data _dataFactory;
       
        /// <summary> 
        /// Empty default constructor. 
        /// </summary> 
        public #spName#Base() {
            _dataFactory = new #spName#Data();
        }
                
        protected #spName#Data DataFactory { 
            get {
                if (_dataFactory == null)
                    _dataFactory = new #spName#Data();
                return _dataFactory;
            } 
        }
    } 

} 