/*
 *  DO NOT EDIT THIS CLASS.
 * 
 *  This class is generated by a tool and should not be edited. If you need to change the functionality of 
 *  this class, you should discuss your changes with the team and they should be implemented in the
 *  appropriate template.
 *  
 */
namespace #rootNamespace#.DataLayer {
    /// <summary>
    /// Column enumeration.
    /// </summary>
    public enum #spName#Fields {#enumFields#
    }
}
