/*
 *  DO NOT EDIT THIS CLASS.
 * 
 *  This class is generated by a tool and should not be edited. If you need to change the functionality of 
 *  this class, you should discuss your changes with the team and they should be implemented in the
 *  appropriate template.
 *  
 */
using System;

namespace #rootNamespace#.BusinessLayer {   
    
    [Serializable()]
    public abstract class #spName#RecordsetBase { 
        
        #region *** Members ***
#protectedFields#
        protected bool _isDirty = false;
        #endregion 

        #region *** Properties ***
        
#publicProperties#
        
        public bool IsDirty { 
            get { return _isDirty; } 
            set { _isDirty = value; } 
        } 
        
        #endregion 
        
        public #spName#RecordsetBase() { 
        }

      /// <summary>
      /// Returns a new instance of the current recordset.
      /// </summary>
      /// <returns></returns>
      public virtual #spName#Recordset Clone() {
          #spName#Recordset new#spName#RS = new #spName#Recordset(); 
          #cloneSettings#
          new#spName#RS.IsDirty = _isDirty;
          return new#spName#RS; 
      }
    }

}