//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Textfyre.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Textfyre.UI.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&lt;Paragraph&gt;&lt;Bold&gt;)(.*?)(&lt;/Bold&gt;&lt;LineBreak/&gt;).
        /// </summary>
        internal static string FyreXML_LocationName_Regex_Search {
            get {
                return ResourceManager.GetString("FyreXML_LocationName_Regex_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Header&gt;$2&lt;/Header&gt;&lt;Paragraph&gt;.
        /// </summary>
        internal static string FyreXML_LocationName_Replacement {
            get {
                return ResourceManager.GetString("FyreXML_LocationName_Replacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;paragraph&gt;.
        /// </summary>
        internal static string FyreXML_Paragraph_Begin {
            get {
                return ResourceManager.GetString("FyreXML_Paragraph_Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/paragraph&gt;.
        /// </summary>
        internal static string FyreXML_Paragraph_End {
            get {
                return ResourceManager.GetString("FyreXML_Paragraph_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;paragraph.
        /// </summary>
        internal static string FyreXML_Paragraph_Partial_Begin {
            get {
                return ResourceManager.GetString("FyreXML_Paragraph_Partial_Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;StoryMode/&gt;&lt;FullPageBreak/&gt;&lt;ColumnScroll/&gt;&lt;AddImagePage/&gt;.
        /// </summary>
        internal static string FyreXML_PrologueContents {
            get {
                return ResourceManager.GetString("FyreXML_PrologueContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PrologueMode/&gt;.
        /// </summary>
        internal static string FyreXML_PrologueMode {
            get {
                return ResourceManager.GetString("FyreXML_PrologueMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/prompt&gt;.
        /// </summary>
        internal static string FyreXML_Prompt_End {
            get {
                return ResourceManager.GetString("FyreXML_Prompt_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;prompt&gt;.
        /// </summary>
        internal static string FyreXML_Prompt_Start {
            get {
                return ResourceManager.GetString("FyreXML_Prompt_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;StoryMode/&gt;.
        /// </summary>
        internal static string FyreXML_StoryMode {
            get {
                return ResourceManager.GetString("FyreXML_StoryMode", resourceCulture);
            }
        }
    }
}
